### ISSUE TITLE
В веб-интерфейсе контроллера Wiren Board не отображаются единицы измерения

### ISSUE THREAD

**Issue by aadegtyarev** [avp-avp/libs#5]
При генерации устройств Wiren Board контролам назначаются неверные типы. Предлагаю исправление, основано на конвенции WEbUI https://github.com/wirenboard/homeui/blob/master/conventions.md

[Brought-the-types-of-controls-in-accordance-with-the.zip](https://github.com/avp-avp/libs/files/7107818/Brought-the-types-of-controls-in-accordance-with-the.zip)

**Comment by avp-avp** [comment]
Спасибо!
